2023-05-29 18:07:26,066 ERROR Internal Server Error: /news/ D:\WORK\Djjjango2\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 3: 'custom_tags'. Did you forget to register or load this tag?"), <traceback object at 0x0000015C0021D580>)
Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'custom_tags'. Did you forget to register or load this tag?
2023-05-29 18:07:26,068 ERROR "GET /news/ HTTP/1.1" 500 186962 D:\WORK\Djjjango2\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-05-30 17:00:15,043 ERROR Internal Server Error: /news/search/ D:\WORK\Djjjango2\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '==' from 'language.code=='"), <traceback object at 0x00000182B53E3740>)
Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: 'language.code=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'language.code=='
2023-05-30 17:00:15,053 ERROR "GET /news/search/ HTTP/1.1" 500 244487 D:\WORK\Djjjango2\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-05-30 17:21:00,815 ERROR Internal Server Error: /news/ D:\WORK\Djjjango2\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 3: 'custom_tags'. Did you forget to register or load this tag?"), <traceback object at 0x00000182B511C940>)
Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\WORK\Djjjango2\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'custom_tags'. Did you forget to register or load this tag?
2023-05-30 17:21:00,816 ERROR "GET /news/ HTTP/1.1" 500 187614 D:\WORK\Djjjango2\venv\lib\site-packages\django\core\servers\basehttp.py None
